### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SpyC0der77** [samuelpapineau/lyric-video-generator#1]
It doesn't work. I did everything and it gives me an error.
@SpyC0der77 ➜ /workspaces/lyric-video-generator (main) $ npm run setup

> lyric-video-generator@1.0.0 setup
> mkdirp ./public/images && mkdirp ./public/lyrics && mkdirp ./public/audio

@SpyC0der77 ➜ /workspaces/lyric-video-generator (main) $ npm run start

> lyric-video-generator@1.0.0 start
> ts-node index.ts

sh: 1: ts-node: not found

**Comment by samuelpapineau** [comment]
Ah nice catch, seems the ts-node dependency was missing. I've updated the package.json, should work now.

**Comment by SpyC0der77** [comment]
Ok thank you. I have been looking for a good lyric video generator, and this looks perfect. I will try it later today.
